import type { Metadata } from "next";
import { Montserrat, Playfair_Display, Anton, Open_Sans, Lato, Roboto } from "next/font/google";
import pages from '@/app/page';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anton = Anton({
  subsets: ["latin"],
  weight: ["400"]
}); 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.className} antialiased`}
      >
        {children}
        <div className="grid grid-rows-4 grid-col-4 border-4 border-black ">

        </div>
      </body>
    </html>
  );
}
