import type { Metadata } from "next";
import {  Playfair_Display, Anton,  } from "next/font/google";
import Cards from "./page";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anton = Anton({
  subsets: ["latin"],
  weight: ["400"]
}); 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.className} antialiased`}
      >
        <div className="grid grid-rows-4 grid-col-4 gap-4 border-4 border-black ">
            <Cards />
        </div>
      </body>
    </html>
  );
}
